FROM brendanburns/php

ADD index.php /var/www/index.php
ADD angular.min.js /var/www/angular.min.js
ADD bootstrap.min.css /var/www/bootstrap.min.css
ADD controllers.js /var/www/controllers.js
ADD index.html /var/www/index.html

CMD /run.sh
